version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  jobs:
    post_create_environment:
      - python -m pip install sphinx_rtd_theme

sphinx:
   configuration: docs/conf.py
   builder: html
   fail_on_warning: false

python:
   install:
     - method: pip
       path: .
